// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASUpPvrcvDuOEI5gHCJX66Xp-RnF_-Kz4',
    appId: '1:1021889924336:web:f53f2c9724142f1bff8635',
    messagingSenderId: '1021889924336',
    projectId: 'banquete-do-monarca-9f145',
    authDomain: 'banquete-do-monarca-9f145.firebaseapp.com',
    storageBucket: 'banquete-do-monarca-9f145.appspot.com',
    measurementId: 'G-T1XXVVYXE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaZV75bY5Ia1N40LB484_FeFsepo5jOHA',
    appId: '1:1021889924336:android:88927309a3930a01ff8635',
    messagingSenderId: '1021889924336',
    projectId: 'banquete-do-monarca-9f145',
    storageBucket: 'banquete-do-monarca-9f145.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAaonx508hnVwfKI3z7O5-qWpcDa242OY',
    appId: '1:1021889924336:ios:3edb410188613e24ff8635',
    messagingSenderId: '1021889924336',
    projectId: 'banquete-do-monarca-9f145',
    storageBucket: 'banquete-do-monarca-9f145.appspot.com',
    iosClientId: '1021889924336-pfr963ob74jf0v216f50unk80nqj0lq0.apps.googleusercontent.com',
    iosBundleId: 'com.example.banqueteDoMonarca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAaonx508hnVwfKI3z7O5-qWpcDa242OY',
    appId: '1:1021889924336:ios:3edb410188613e24ff8635',
    messagingSenderId: '1021889924336',
    projectId: 'banquete-do-monarca-9f145',
    storageBucket: 'banquete-do-monarca-9f145.appspot.com',
    iosClientId: '1021889924336-pfr963ob74jf0v216f50unk80nqj0lq0.apps.googleusercontent.com',
    iosBundleId: 'com.example.banqueteDoMonarca',
  );
}
